name: CI Lambda

on:
  pull_request:
    branches: [master]
env:
  node_version: "14.x"

jobs:
  image:
    name: Build, Audit, & Lint the Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: lambda
        run: docker build .
